apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
      - name: pvc-nfs-claim
        mountPath: "/data"
  volumes:
    - name: pvc-nfs-claim
      persistentVolumeClaim:
        claimName: myclaim