apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-default-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true

---

#Retain the volume


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-default-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true
